In [39]:
import numpy as np

data = np.genfromtxt('baseball.csv', delimiter=',', skip_header=1)#We skip the header becasue it has the description
print(data.shape)
print()
print(data[:2])  # show first 2 players
print()
#print("the home runs are listed below")
#print(data[:, -1])  #Extract and print the “HomeRuns” column for all players.

#for hr in data[:, -1]: #Extract and print the “HomeRuns” column for all players. in a vertical line
#    print(hr)

mask = data[:, -1] > 20  #Filter the dataset to select only players who have hit more than 20 home runs.

print(data[mask])
filtered_data = data[mask]
print("the avaerage of player who hit more than 20 homeruns is", np.mean(filtered_data[:,-1])) #Calculate and print the average number of home runs among these players.
print("the number who scored more than 20 is", filtered_data.shape[0]) #is to also print the number of players who hit more than 20 Homeruns



(50, 6)

[[187.  81.  28. 105. 319.   6.]
 [184.  78.  33.  66. 360.  25.]]

[[184.  78.  33.  66. 360.  25.]
 [188.  78.  27.  65. 363.  23.]
 [182.  77.  25. 119. 283.  21.]
 [182.  79.  27. 129. 311.  21.]
 [176.  84.  20. 108. 292.  25.]
 [177.  76.  31.  69. 393.  28.]
 [192.  81.  33. 120. 253.  21.]
 [185.  79.  21.  82. 388.  25.]
 [185.  84.  24.  50. 267.  24.]
 [179.  80.  20.  60. 232.  25.]
 [186.  78.  27. 106. 341.  27.]
 [181.  78.  20.  80. 347.  22.]
 [194.  81.  21.  91. 327.  29.]
 [179.  77.  31.  65. 334.  26.]
 [175.  81.  20.  97. 232.  28.]
 [178.  77.  20.  61. 375.  22.]
 [188.  80.  33.  86. 314.  26.]
 [185.  84.  21.  81. 318.  27.]
 [181.  72.  25. 129. 308.  21.]]
the avaerage of player who hit more than 20 homeruns is 24.526315789473685
the number who scored more than 20 is 19


In [54]:

print("Have any players hit more than 50 homeruns =",np.any(data[:, -1]>50))         #Check if any player hit more than 50 home runs.
print("Are all players taller than 150 cm =",np.all(data[:,0]>150))                  #Check if all players are taller than 150 cm.
mask = (data[:,-1]>20) & (data[:,-2]>0.250)                                          #players who have more than 20 home runs AND a batting average above 0.250
print(data[mask])

Have any players hit more than 50 homeruns = False
Are all players taller than 150 cm = True
[[184.  78.  33.  66. 360.  25.]
 [188.  78.  27.  65. 363.  23.]
 [182.  77.  25. 119. 283.  21.]
 [182.  79.  27. 129. 311.  21.]
 [176.  84.  20. 108. 292.  25.]
 [177.  76.  31.  69. 393.  28.]
 [192.  81.  33. 120. 253.  21.]
 [185.  79.  21.  82. 388.  25.]
 [185.  84.  24.  50. 267.  24.]
 [179.  80.  20.  60. 232.  25.]
 [186.  78.  27. 106. 341.  27.]
 [181.  78.  20.  80. 347.  22.]
 [194.  81.  21.  91. 327.  29.]
 [179.  77.  31.  65. 334.  26.]
 [175.  81.  20.  97. 232.  28.]
 [178.  77.  20.  61. 375.  22.]
 [188.  80.  33.  86. 314.  26.]
 [185.  84.  21.  81. 318.  27.]
 [181.  72.  25. 129. 308.  21.]]
